USE DATABASE FEATURESTORE_DB; -- noqa: PRS
USE SCHEMA FEATURESTORE_SCHEMA;
USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE NOTIFICATION INTEGRATION EMAIL_INT
TYPE=EMAIL -- noqa: PRS
ENABLED=TRUE
ALLOWED_RECIPIENTS=('dishaaagarwal.100@gmail.com');

GRANT OWNERSHIP ON INTEGRATION EMAIL_INT TO ROLE FEATURESTORE_ROLE;
GRANT USAGE ON INTEGRATION EMAIL_INT TO ROLE FEATURESTORE_ROLE;
