repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        # language_version: python3.10
        # auto_commit: true
  # - repo: https://github.com/sqlfluff/sqlfluff
  #   rev: stable  # Use the desired version of sqlfluff
  #   hooks:
  #     - id: sqlfluff-lint
  #       args: [ '--dialect=snowflake' ]
